In [1]:
import numpy as np
import numpy.linalg as la

We can construct identity matrices using the numpy.identity(n) and numpy.eye(n) functions. The former constructs an n x n square matrix with 1s along the leading diagonal.

The latter constructs an n x m matrix with 1s along the kth diagonal, where k=0 can be specified as the main diagonal.

In [2]:
#Square 5*5 matrix:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
#4*5 matrix using np.eye
print(np.eye(4, 5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [4]:
#4*5 matrix with k specified as -1 
#this shifts the leading diagonal 1 to the left
print(np.eye(4, 5, -1))

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [5]:
#4*5 matrix with k specified as 2
#this shifts the leading diagonal 2 to the right
print(np.eye(4, 5, 2))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


**Diagonal matrices**

np.diag can be used to extract a diagonal from a given matrix; if the input array is 2D, the output of np.diag is a 1D array with diagonal entries 
If the input is 1d, the output of np.diag is a 2D array with entries along the diagonal

In [11]:
M = np.array([[1, 2], [3, 4]])
N = np.array([1, 2, 3, 4])

#1D array of diagonal values
print(f" {np.diag(M)} \n")

#2D array with values along leading diagonal
print(np.diag(N))

 [1 4] 

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [13]:
a = [1, 1, 1]
b = [2, 3, 5, 4]
c = [3, 1, 5]

#Produces a tri-diagonal matrix, which has 
#values along the leading diagonal and diagonals
#either side of it

A = np.diag(b, 0) + np.diag(a, -1) + np.diag(c, 1)
print(A)

[[2 3 0 0]
 [1 3 1 0]
 [0 1 5 5]
 [0 0 1 4]]


**Constructing an upper and lower triangular matrix**

This can be done using the functions **numpy.triu** and **numpy.tril**. The array whose entries below or above the kth diagonal are 0 

In [21]:
M = np.arange(1, 13).reshape(4, 3)
print(f"{M} \n")

#Upper triangular matrix below the leading diagonal
print(f"{np.triu(M, -1)} \n")

#Lower triangular matrix above the leading diagonal
print(f"{np.tril(M, 0)} \n")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 0  8  9]
 [ 0  0 12]] 

[[ 1  0  0]
 [ 4  5  0]
 [ 7  8  9]
 [10 11 12]] 



**Producing sparse matrices**

Sparse matrix = mostly zero-valued entries 

When working with sparse matrices, we may prefer to skip certain operations which will result in uncessary adding and multiplication of 0's. 

using the **scipy.sparse** package we can build and carry out operations on sparse matrices. 

In [27]:
from scipy.sparse import coo_matrix

a, b, c = [1] * 9, [2] * 10, [3] * 9
print(f"1: {a, b, c} \n")

#tridiagonal matrix from given arrays
A = np.diag(a, -1) + np.diag(b, 0) + np.diag(c, 1)
print(f"2: {A} \n")

#conversion to a sparse SciPy matrix
spA = coo_matrix(A)
print(f"3: {spA}")

1: ([1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [3, 3, 3, 3, 3, 3, 3, 3, 3]) 

2: [[2 3 0 0 0 0 0 0 0 0]
 [1 2 3 0 0 0 0 0 0 0]
 [0 1 2 3 0 0 0 0 0 0]
 [0 0 1 2 3 0 0 0 0 0]
 [0 0 0 1 2 3 0 0 0 0]
 [0 0 0 0 1 2 3 0 0 0]
 [0 0 0 0 0 1 2 3 0 0]
 [0 0 0 0 0 0 1 2 3 0]
 [0 0 0 0 0 0 0 1 2 3]
 [0 0 0 0 0 0 0 0 1 2]] 

3:   (0, 0)	2
  (0, 1)	3
  (1, 0)	1
  (1, 1)	2
  (1, 2)	3
  (2, 1)	1
  (2, 2)	2
  (2, 3)	3
  (3, 2)	1
  (3, 3)	2
  (3, 4)	3
  (4, 3)	1
  (4, 4)	2
  (4, 5)	3
  (5, 4)	1
  (5, 5)	2
  (5, 6)	3
  (6, 5)	1
  (6, 6)	2
  (6, 7)	3
  (7, 6)	1
  (7, 7)	2
  (7, 8)	3
  (8, 7)	1
  (8, 8)	2
  (8, 9)	3
  (9, 8)	1
  (9, 9)	2


This has reduced the number of entries in A (100) to just 28 in spA. 
The large the matrix, the higher the computational savings

We can also use the **scipy.sparse import diags** library to construct sparse matrices directly from SciPy, rather than converting a NumPy array. 

In [31]:
from scipy.sparse import diags

diagonals = [[1] * 9, [2] * 10, [3] * 9]

A = diags(diagonals, [-1, 0, 1], format='coo')
print(f"1: {A.toarray()} \n")
print(f"2: {A}")

1: [[2. 3. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 2. 3. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 2. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 2. 3. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 2. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 2. 3.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 2.]] 

2:   (1, 0)	1.0
  (2, 1)	1.0
  (3, 2)	1.0
  (4, 3)	1.0
  (5, 4)	1.0
  (6, 5)	1.0
  (7, 6)	1.0
  (8, 7)	1.0
  (9, 8)	1.0
  (0, 0)	2.0
  (1, 1)	2.0
  (2, 2)	2.0
  (3, 3)	2.0
  (4, 4)	2.0
  (5, 5)	2.0
  (6, 6)	2.0
  (7, 7)	2.0
  (8, 8)	2.0
  (9, 9)	2.0
  (0, 1)	3.0
  (1, 2)	3.0
  (2, 3)	3.0
  (3, 4)	3.0
  (4, 5)	3.0
  (5, 6)	3.0
  (6, 7)	3.0
  (7, 8)	3.0
  (8, 9)	3.0


**MATRIX OPERATIONS -  Arithmetic Operations**

All arithmetic operators on arrays apply elementwise. 
If both operands are matrices, they need the same dimensions to be conformable for the operation.

In [35]:
M = np.array([[1, 2], 
              [3, 4]])

In [46]:
#Add matrices
print(f"1: {M+M} \n")

#Subtract matrices
print(f"2: {M-M} \n")

#multiply a matrix by a scalar
print(f"3: {4*M} \n")

#multiply matrices elementwise
print(f"4: {M*M} \n")

#divide matrices elementwise
print(f"5: {M/M} \n")

#exponentiation elementwise
print(f"6: {M**3} \n")

#Modulo of the matrix elementwise
print(f"7: {M%2} \n")

#Integer (floor) divsion for matrix elements 
print(f"8: {M // 2} \n")

1: [[2 4]
 [6 8]] 

2: [[0 0]
 [0 0]] 

3: [[ 4  8]
 [12 16]] 

4: [[ 1  4]
 [ 9 16]] 

5: [[1. 1.]
 [1. 1.]] 

6: [[ 1  8]
 [27 64]] 

7: [[1 0]
 [1 0]] 

8: [[0 1]
 [1 2]] 



**MATRIX MULTIPLICATION**

The numpy function **np.matul(array1, array2)** can be used to multiply two matrices together 
We can also use the @ function

The **np.linalg.matrix_power(array, exp)** function can be called to raise a matrix to some power 


In [52]:
#Right-multiplies M by M 
print(f"1: {M@M} \n")

#Right-multiplies M by M by M
print(f"2: {M@M@M} \n")


#Raises a matrix to the third power, i.e. right-multiplies
# M by M by M
print(f"3: {la.matrix_power(M, 3)}")

1: [[ 7 10]
 [15 22]] 

2: [[ 37  54]
 [ 81 118]] 

3: [[ 37  54]
 [ 81 118]]


In [57]:
x = np.array([1,2])
print(f"1: {x}")

#Vector-matrix multiplication
print(f"2: {x @ M}")

#Matrix-vector multiplication
print(f"3: {M @ x}")

1: [1 2]
2: [ 7 10]
3: [ 5 11]


**Inner Product:**
The **np.dot** function is a dot product used to calculate the inner product of two vectors. 

In [59]:
x = np.array([1, 2])
y = np.array([3, 4])

print(np.dot(x, y))

11


**Transpose:** The **np.transpose** function can be used to transpose a matrix
The array attribute **array.T** can also be called

In [65]:
M = np.array([[1, 2], 
              [3, 4]])
print(f"1: {M} \n")

#transpose of matrix M using the array attribute 
print(f"2: {M.T} \n")

#transpose of matrix M using the transpose of
#numpy

print(f"3: {np.transpose(M)}")

1: [[1 2]
 [3 4]] 

2: [[1 3]
 [2 4]] 

3: [[1 3]
 [2 4]]


1D arrays remain unchanged when transposed; so, column/row vectors should be initialised as 2D arrays with dimensions (n x 1) or (1 x n). 

If we start from a 1D array of 4 entries, we can generate an array of shape k x 1 x 2 

In [73]:
#One-dimensional np array

x = np.array([1, 2, 3])
print(f"1: {x},\n 2: {x.ndim},\n 3: {x.shape}")
print(f"4: {x.T}")

1: [1 2 3],
 2: 1,
 3: (3,)
4: [1 2 3]


In [77]:
#Make the array two-dimensional with dimensions 
#[1, k]
x = np.array([[1, 2, 3]])
print(f"1: {x},\n 2: {x.ndim},\n 3: {x.shape}\n")
print(f"4: {x.T}")

#As seen, the matrix is now transposed unlike the 
#1D array above

1: [[1 2 3]],
 2: 2,
 3: (1, 3)

4: [[1]
 [2]
 [3]]


In [80]:
#We can also use the reshape attribute to transpose
#the matrix 
x = np.array([1, 2, 3]).reshape(-1, 1)
print(f"1: {x},\n 2: {x.ndim},\n 3: {x.shape}")

1: [[1]
 [2]
 [3]],
 2: 2,
 3: (3, 1)


**Complex Conjugate:**
We can use the **np.conjugate** attribute to find the complex conjugate of an array with complex numbers in its entries
We can obtain the conjugate/Hermitian transpose by calling the **array.T.conj()**

In [83]:
C = np.array([[1 + 1j, 2 + 2j],
              [3 + 3j, 4 + 4j]])

print(f"1: {C}\n")

#conjugate using the np.conjugate function 
print(f"2: {np.conj(C)}\n")

#conjugate of the transpose using the 
#array.T.conj attribute
print(f"3: {C.T.conj()}")

1: [[1.+1.j 2.+2.j]
 [3.+3.j 4.+4.j]]

2: [[1.-1.j 2.-2.j]
 [3.-3.j 4.-4.j]]

3: [[1.-1.j 3.-3.j]
 [2.-2.j 4.-4.j]]


**NORMS:** We can call the **np.linalg.norm** function to return a matrix or vector norm. 
If no [order] argument is passed into the function, the Frobenius/2-norm is passed to the matrix

In [87]:
x = np.array([1, 2, 3])
M = np.array([[1, 2],
              [3, 4]])

#calculating the first-order norm of the vector
print(f"1: {la.norm(x, 1)}\n")

print(f"2: {la.norm(x)}\n")

print(f"3: {la.norm(x, np.inf)}")

1: 6.0

2: 3.7416573867739413

3: 3.0


In [88]:
#Calculating the norm of the matrix M
print(f"1: {la.norm(M)}\n")

print(f"2: {la.norm(M, np.inf)}\n")

1: 5.477225575051661

2: 7.0



**MATRIX INVERSE:** We can use **np.linalg.inv** to find the inverse of a square matrix.
An inverse is likely to be imprecise due to round-off errors with larger errors 

In [89]:
print(f"1: {la.inv(M)}")

1: [[-2.   1. ]
 [ 1.5 -0.5]]


**USING MATRIX MATHS TO SOLVE LINEAR EQUATION SYSTEMS:**
Ax = b
the **np.linalg.solve** function will solve the equation for x, without the requirement for finding an inverse and using the equation A-1b = x 


In [90]:
A = np.array([[3, 5, -1],
              [1, 4, 1 ],
              [9, 0, 2 ]])
b = np.array([10, 7, 1])

x = np.linalg.solve(A, b)
print(x)

[ 0.2  1.8 -0.4]
