In [33]:
import numpy as np
import scipy.linalg as sl

Code to construct the inverse of a matrix

In [34]:
def upper_triangle(A,B):
    n, m = np.shape(A)
    assert(n == m) #assert matrix is square
    
    for k in range(n-1):
        for i in range(k+1, n):
            s = (A[i, k]/A[k, k])
            for j in range(n):
                A[i,j] = A[i,j] - s*A[k,j]
                B[i,k] = B[i,j] - s*B[k,j]
                
def lower_triangle(A,B):
    #the rationale of having an upper and lower triangular 
    #function is that if you feed a matrix into them one after another, 
    #you get a diagonal matrix
    n, m = np.shape(A)
    assert(n==m)
    
    for k in range(n-1, -1, -1):
        for i in range(k-1, -1, -1): #notice that these loops iterate through the 
                                     #lists in inverse order to the upper triangular function
            s = (A[i,k]/A[k,k])
            for j in range(n):
                A[i,j] = A[i,j] - s*A[k,j]
                B[i,j] = B[i,j] - s*B[k,j]
    

Application of A,B to a given matrix array

In [35]:
A = np.array([[2, 3, -4],
            [3,-1,2],
            [4,2,2]])

#b is an identity matrix with a corresponding size
B = np.eye(np.shape(A)[0])

#transform A into upper triangular form
# and perform that operation on B
upper_triangle(A, B)
print('Upper triangular transformed A = ')
print(A)

#Now make lower triangular as well, to produce a diagonal matrix
lower_triangle(A, B)
print('\nAnd following application of our lower triangular function = ')
print(A)

#Divide each row through by the value of the 
#diagonal to end up with 1's on the main diagonal
#and 0 everywhere else.
for i in range(np.shape(A)[0]):
    B[i, :] = B[i, :]/A[i,i]
    A[i, :] = A[i, :]/A[i,i]
    
print('\nOur final transformed A = ')
print(A)

print('\nand the correspondingly transformed B = ')
print(B)

A = np.array([[2, 3, -4], [3, -1, 2], [4, 2, 2]])
print('\nSciPy computes the inverse as: ')
print(sl.inv(A))

print('\nSuccess: ', np.allclose(B, sl.inv(A)))

Upper triangular transformed A = 
[[ 2  3 -4]
 [ 0 -5  8]
 [ 0  0  3]]

And following application of our lower triangular function = 
[[ 2  0  0]
 [ 0 -5  0]
 [ 0  0  3]]

Our final transformed A = 
[[1 0 0]
 [0 1 0]
 [0 0 1]]

and the correspondingly transformed B = 
[[ 0.36666667  0.16666667 -0.13333333]
 [ 0.53333333  0.33333333  0.53333333]
 [ 0.33333333  0.33333333  0.33333333]]

SciPy computes the inverse as: 
[[ 0.13043478  0.30434783 -0.04347826]
 [-0.04347826 -0.43478261  0.34782609]
 [-0.2173913  -0.17391304  0.23913043]]

Success:  False


Upper triangular transformed A = 
[[ 2.          3.         -4.        ]
 [ 0.         -5.5         8.        ]
 [ 0.          0.          4.18181818]]

and following application of our lower triangular function = 
[[ 2.          0.          0.        ]
 [ 0.         -5.5         0.        ]
 [ 0.          0.          4.18181818]]

Our final transformed A = 
[[ 1.  0.  0.]
 [-0.  1. -0.]
 [ 0.  0.  1.]]

and the correspondingly transformed B = 
[[ 0.13043478  0.30434783 -0.04347826]
 [-0.04347826 -0.43478261  0.34782609]
 [-0.2173913  -0.17391304  0.23913043]]

SciPy computes the inverse as:
[[ 0.13043478  0.30434783 -0.04347826]
 [-0.04347826 -0.43478261  0.34782609]
 [-0.2173913  -0.17391304  0.23913043]]

Success:  True
